### ISSUE TITLE
"node diaonao.js" error in mac os

### ISSUE THREAD

**Issue by proguy** [phodal/diaonan#1]
node diaonan.js 

dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/van/diaonan/node_modules/ascoltatori/node_modules/mongodb/node_modules/bson/build/Release/bson.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/van/diaonan/node_modules/ascoltatori/node_modules/mongodb/node_modules/bson/build/Release/bson.node
  Expected in: dynamic lookup

Trace/BPT trap: 5

node -v
v0.10.36

redis-server -v
Redis server v=2.8.19 sha=00000000:0 malloc=libc bits=64 build=41d8fd47220dc567

**Comment by phodal** [comment]
试着

     sudo rm -rf node_modules

然后再安装一次

     sudo npm install
